name: build and test

on:
  push:
    branches: [ "master", "dev" ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ "master", "dev" ]
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true

      # Set up a matrix to run the following 3 configurations:
      # 1. <Windows, Release, latest MSVC compiler toolchain on the default runner image, default generator>
      # 2. <Linux, Release, latest GCC compiler toolchain on the default runner image, default generator>
      # 3. <Linux, Release, latest Clang compiler toolchain on the default runner image, default generator>
      #
      # To add more build types (Release, Debug, RelWithDebInfo, etc.) customize the build_type list.
      matrix:
        os: [ubuntu-latest]
        build_type: [Release]
        redis_version: [7.2.8]
        c_compiler: [gcc, clang]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v4

    - name: libuv-dep
      run: |
        sudo apt-get update
        sudo apt-get install -yq libuv1-dev wget unzip

    - name: redis-dep
      run: |
        wget -L https://github.com/redis/redis/archive/refs/tags/${{matrix.redis_version}}.zip -O redis-${{matrix.redis_version}}.zip
        unzip redis-${{matrix.redis_version}}.zip
        cd redis-${{matrix.redis_version}}
        make -j2
        ./src/redis-server --port 7000 --cluster-enabled yes --cluster-config-file nodes-7000.conf --daemonize yes
        ./src/redis-server --port 7001 --cluster-enabled yes --cluster-config-file nodes-7001.conf --daemonize yes
        ./src/redis-server --port 7002 --cluster-enabled yes --cluster-config-file nodes-7002.conf --daemonize yes
        sleep 2
        ./src/redis-cli --cluster-yes --cluster create 127.0.0.1:7000 127.0.0.1:7001 127.0.0.1:7002 && ./src/redis-server --daemonize yes

    - name: hiredis-dep
      run: |
        wget -L https://github.com/redis/hiredis/archive/master.zip -O hiredis-master.zip && unzip hiredis-master.zip && mkdir -p ${{ github.workspace }}/install
        cd hiredis-master && make PREFIX=${{ github.workspace }}/install -j2 install && cd ..

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DCMAKE_PREFIX_PATH=${{ github.workspace }}/install
        -DREDIS_PLUS_PLUS_BUILD_ASYNC=libuv
        -S ${{ github.workspace }}

    - name: Build
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ./test/test_redis++ -h 127.0.0.1 -p 6379 -n 127.0.0.1 -c 7000

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ninja and memurai
        run: choco install -y ninja memurai-developer

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git vcpkg
          .\vcpkg\bootstrap-vcpkg.bat
  
      - name: Install Hiredis using vcpkg
        run: .\vcpkg\vcpkg install hiredis

      - uses: ilammy/msvc-dev-cmd@v1
      - name: build hiredis
        run: |
          mkdir build
          cd build
          cmake -G Ninja `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_PREFIX_PATH="${{ github.workspace }}/install;${{ github.workspace }}/vcpkg/installed/x64-windows" `
            .. && `
          ninja -v && `
          ninja install
